name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.dataStep.outputs.matrix }}
    steps:
      - uses: actions/checkout@v1
      - id: dataStep
        run: |
          set -x
          ./gradlew setupBuild
          echo "matrix=$(cat output.json)" >> $GITHUB_OUTPUT
  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v1
      - run: ./gradlew ${{matrix.task}}